env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  no-unused-vars:
    - warn
  indent:
    - error
    - 2
  linebreak-style:
    - 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/prop-types:
    - 0
