name: Build and Deploy
on:
  push:
    branches: dev-vite
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Node.js 🗿
        uses: actions/setup-node@v6
        with:
          node-version: '24.x' # Specify your required Node.js version

      - name: Install 💾
        run: npm ci

      - name: Build 🔧
        run: npm run build --if-present

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          # branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
